### ISSUE TITLE
Doesn't Work 😒

### ISSUE THREAD

**Issue by FaatehSiddique** [PiggyAwesome/discord-token-onliner-py#1]
Exception in thread Thread-5 (main):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 135, in main
    socket = DiscordWebSocket()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 54, in __init__
    self.websocket_instance = connect("wss://gateway.discord.gg/?v=10&encoding=json")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 283, in connect
    connection = create_connection(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 58, in __init__
Exception in thread Thread-4 (main):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    super().__init__(
Exception in thread Thread-2 (main):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\site-packages\websockets\sync\connection.py", line 89, in __init__
  File "C:\Python312\Lib\threading.py", line 989, in run
    self.run()
    self.recv_events_thread.start()
  File "C:\Python312\Lib\threading.py", line 971, in start
  File "C:\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
    _start_new_thread(self._bootstrap, ())
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 135, in main
RuntimeError: can't create new thread at interpreter shutdown
    self._target(*self._args, **self._kwargs)
    socket = DiscordWebSocket()
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 135, in main
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 54, in __init__
    socket = DiscordWebSocket()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 54, in __init__
    self.websocket_instance = connect("wss://gateway.discord.gg/?v=10&encoding=json")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self.websocket_instance = connect("wss://gateway.discord.gg/?v=10&encoding=json")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 283, in connect
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 283, in connect
    connection = create_connection(
    connection = create_connection(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 58, in __init__
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 58, in __init__
    super().__init__(
  File "C:\Python312\Lib\site-packages\websockets\sync\connection.py", line 89, in __init__
    super().__init__(
  File "C:\Python312\Lib\site-packages\websockets\sync\connection.py", line 89, in __init__
    self.recv_events_thread.start()
  File "C:\Python312\Lib\threading.py", line 971, in start
    self.recv_events_thread.start()
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
  File "C:\Python312\Lib\threading.py", line 971, in start
Exception in thread Thread-6 (main):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
Exception in thread Thread-3 (main):
Traceback (most recent call last):
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
  File "C:\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 989, in run
    self.run()
  File "C:\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 135, in main
    self._target(*self._args, **self._kwargs)
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 135, in main
    socket = DiscordWebSocket()
Exception in thread Thread-1 (main):
    socket = DiscordWebSocket()
             ^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 54, in __init__
    self.run()
  File "C:\Python312\Lib\threading.py", line 989, in run
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 54, in __init__
    self.websocket_instance = connect("wss://gateway.discord.gg/?v=10&encoding=json")
    self._target(*self._args, **self._kwargs)
    self.websocket_instance = connect("wss://gateway.discord.gg/?v=10&encoding=json")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 135, in main
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 283, in connect
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    socket = DiscordWebSocket()
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 283, in connect
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\faate\OneDrive\Desktop\discord-token-onliner-py-main\discord-token-onliner-py-main\main.py", line 54, in __init__
    connection = create_connection(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 58, in __init__
    self.websocket_instance = connect("wss://gateway.discord.gg/?v=10&encoding=json")
    connection = create_connection(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 283, in connect
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 58, in __init__
    super().__init__(
    connection = create_connection(
    super().__init__(
  File "C:\Python312\Lib\site-packages\websockets\sync\connection.py", line 89, in __init__
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\websockets\sync\connection.py", line 89, in __init__
  File "C:\Python312\Lib\site-packages\websockets\sync\client.py", line 58, in __init__
    self.recv_events_thread.start()
    self.recv_events_thread.start()
  File "C:\Python312\Lib\threading.py", line 971, in start
  File "C:\Python312\Lib\threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown
    _start_new_thread(self._bootstrap, ())
    super().__init__(
RuntimeError: can't create new thread at interpreter shutdown
  File "C:\Python312\Lib\site-packages\websockets\sync\connection.py", line 89, in __init__
    self.recv_events_thread.start()
  File "C:\Python312\Lib\threading.py", line 971, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

**Comment by PiggyAwesome** [comment]
Hi, could you please provide more information?

**Comment by PiggyAwesome** [comment]
I assume issue is fixed as author won't reply
