### ISSUE TITLE
Bug Script

### ISSUE THREAD

**Issue by NightLady0** [PiggyAwesome/discord-token-onliner-py#6]
![photo_2024-03-31_17-26-04](https://github.com/PiggyAwesome/discord-token-onliner-py/assets/136980753/bf5101a8-62d9-4a36-9fba-3155b4d52437)

```
C:\Users\Juno Arcove\Desktop\discord-token-onliner-py-main>python main.py
Traceback (most recent call last):
  File "C:\Users\Juno Arcove\Desktop\discord-token-onliner-py-main\main.py", line 369, in <module>
    config: Dict[str, Union[List[str], Dict[str, List[str]]]] = json.loads(config_file.read())
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 11 column 13 (char 367)
```

**Config :**

```
{
    "choose_random_online_status_from": ["dnd"],
    "choose_random_activity_type_from": ["listening"],
    "listening": {
        "choose_random_name_from": ["Spotify"]
    },
    "listening": {
        "choose_random_name_from": [
            "Spotify",
            "https://open.spotify.com/intl-fr/track/4Bts64N4oyorK045CU7xDd?si=8c82d8c4e3294a28",
            // Add more listening options here
        ]
    } 
}
```
![image](https://github.com/PiggyAwesome/discord-token-onliner-py/assets/136980753/6d9f168a-0b92-4896-b7ed-53f23d774806)

**Comment by PiggyAwesome** [comment]
It seems like you have the "listening" field listed twice. Remove one of them from your config and it will work fine

**Comment by NightLady0** [comment]
> It seems like you have the "listening" field listed twice. Remove one of them from your config and it will work fine

Can u give me the right code ?

**Comment by PiggyAwesome** [comment]
> > It seems like you have the "listening" field listed twice. Remove one of them from your config and it will work fine
> 
> Can u give me the right code ?

{
    "choose_random_online_status_from": ["dnd"],
    "choose_random_activity_type_from": ["listening"],
    "listening": {
        "choose_random_name_from": [
            "Spotify",
            "https://open.spotify.com/intl-fr/track/4Bts64N4oyorK045CU7xDd?si=8c82d8c4e3294a28",
            // Add more listening options here
        ]
    } 
}

As you can see, I removed the first listening field

**Comment by NightLady0** [comment]
> > > It seems like you have the "listening" field listed twice. Remove one of them from your config and it will work fine
> > 
> > 
> > Can u give me the right code ?
> 
> ```json
> {
>     "choose_random_online_status_from": ["dnd"],
>     "choose_random_activity_type_from": ["listening"],
>     "listening": {
>         "choose_random_name_from": [
>             "Spotify",
>             "https://open.spotify.com/intl-fr/track/4Bts64N4oyorK045CU7xDd?si=8c82d8c4e3294a28"
>         ]
>     } 
> }
> ```
> 
> As you can see, I removed the first listening field. I also removed the part with the `//` (comments) as this will usually not work in `.json` files. I only put it there in the documentation to explain what the setting does. Lastly, I removed the comma (`,`) at the end because it should only be there if there is still items being listed after it.

![image](https://github.com/PiggyAwesome/discord-token-onliner-py/assets/136980753/43bc12f8-d9eb-4bef-a0ce-b6975ef0dbe8)

Now it tells me that I didn't put the right token, even though I put the right token.

**Comment by NightLady0** [comment]
Answer fr ?
